### ISSUE TITLE
ES2 support

### ISSUE THREAD

**Issue by popovae** [opendatasoft/elasticsearch-plugin-geoshape#6]
Hi,

Really interesting plugin you made, nice job!
Is there any way it can support ES2.0?

Thank you!

**Comment by clement-tourriere** [comment]
Hi, I will release an ES 2.0 version soon.

**Comment by hanrw** [comment]
+1

**Comment by samchorlton** [comment]
+1

**Comment by SeijiIto** [comment]
+1

**Comment by jezgomez** [comment]
+1

**Comment by jezgomez** [comment]
@clement-tourriere what's involved with getting it working with EX2.x?

**Comment by xando** [comment]
Probably question to anyone in this thread. Is there a working alternative / workaround for ES2?

**Comment by popovae** [comment]
@xando Native es geo-cell aggregation works fine, sometimes even faster...the only downside is there is no way to control cell size more precisely...

**Comment by xando** [comment]
Thanks @popovae for the reply, 

You mean Geohashgrid? 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html

If yes, then indeed it works well, although it grid based so results look a bit artificial. If you meant something else please let me know.

**Comment by popovae** [comment]
Yes, that what i was talking about. Dig into the code and you will see that this plugin is also grid-based...also thought it is based on geodistance...

**Comment by popovae** [comment]
@xando...forgot to mention you)

**Comment by popovae** [comment]
@xando, you can check it easily- take two points close to the enge of one geo-cell and two points on close to the previous ones, but in another geocell...look at the result;)

**Comment by xando** [comment]
@popovae thanks for the input, this is really interesting. Will check it out.

**Comment by clement-tourriere** [comment]
Thank you all for your interest in this plugin. 
I'm currently working on a version for Elasticsearch 2.3, especially for serving mapbox vector tiles.

In Elasticsearch 2.3, it is possible to use directly a geohash grid bucket aggregation with a geo centroid metric aggregation to produce results close to geohash_clustering aggregation in this plugin. The main difference, is the possibility to use geo distance instead of geohash level.

**Comment by dvsathish** [comment]
@clement-tourriere - Thanks for your effort.
Is there a way to apply aggregation on GeoShapes using Elasticsearch 2.3? Basically we will be indexing GeoShapes with different Shape types "point", "linestring","polygon". So when we search by providing lat lon, then all shapes under the bounding box needs to be aggregated and show the doc count. Is there a way to do it?

**Comment by lihuadong1988** [comment]
when to release es 2.3 version?

**Comment by lihuadong1988** [comment]
@clement-tourriere hi,have you ever finished the version for Elasticsearch 2.3?

**Comment by clement-tourriere** [comment]
It's been a while, but geohash aggregation has now its own repository and is compatible with elasticsearch 6+.
https://github.com/opendatasoft/elasticsearch-aggregation-geoclustering
